import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/layout/navbar";
import ScrollProgress from "@/components/ui/scroll-progress";
import Providers from "@/api/provider";
import { Toaster } from "@/components/ui/sonner";
import Footer from "@/components/layout/footer";
import FloatingActionButton from "@/components/floating-action-button";
import ScrollToTop from "@/components/scroll-to-top";
import { getGlobalData } from "@/lib/shared/globalData";

const promptFont = Prompt({
  variable: "--font-prompt",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "NewWav",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // You can fetch data here if needed, but for now, we are just returning the layout
  const data = await getGlobalData();
  // console.log(data); // For debugging purposes
  return (
    <html lang="en">
      <body className={`${promptFont.variable} antialiased overflow-x-hidden`}>
        <Providers>
          <main className="min-h-screen bg-background text-white">
            <ScrollProgress />
            <NavBar />
            {children}
            <Toaster />
          </main>
          <FloatingActionButton data={data} />
          <ScrollToTop />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
