import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/layout/navbar";
import ScrollProgress from "@/components/ui/scroll-progress";
import Providers from "@/api/provider";

const promptFont = Prompt({
  variable: "--font-prompt",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "NewWav",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${promptFont.variable} antialiased overflow-x-hidden`}>
        <Providers>
          <main className="min-h-screen bg-background text-white">
            <ScrollProgress />
            <NavBar />
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
